// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbal

import (
	"time"
)

type AppState struct {
	AppName   string
	State     string
	UpdatedAt time.Time
}

type Session struct {
	SessionID string
	AppName   string
	UserID    string
	State     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type SessionEvent struct {
	ID        string
	SessionID string
	AppName   string
	UserID    string
	EventJson string
	Timestamp time.Time
}

type UserState struct {
	AppName   string
	UserID    string
	State     string
	UpdatedAt time.Time
}
