// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: silo_query.sql

package dbal

import (
	"context"
	"time"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (session_id, app_name, user_id, state, created_at, updated_at)
VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
`

type CreateSessionParams struct {
	SessionID string
	AppName   string
	UserID    string
	State     string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.SessionID,
		arg.AppName,
		arg.UserID,
		arg.State,
	)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE app_name = ? AND user_id = ? AND session_id = ?
`

type DeleteSessionParams struct {
	AppName   string
	UserID    string
	SessionID string
}

func (q *Queries) DeleteSession(ctx context.Context, arg DeleteSessionParams) error {
	_, err := q.db.ExecContext(ctx, deleteSession, arg.AppName, arg.UserID, arg.SessionID)
	return err
}

const getAppState = `-- name: GetAppState :one
SELECT state FROM app_states WHERE app_name = ?
`

func (q *Queries) GetAppState(ctx context.Context, appName string) (string, error) {
	row := q.db.QueryRowContext(ctx, getAppState, appName)
	var state string
	err := row.Scan(&state)
	return state, err
}

const getEventsAfterTimestamp = `-- name: GetEventsAfterTimestamp :many
SELECT id, session_id, app_name, user_id, event_json, timestamp
FROM session_events
WHERE app_name = ? AND user_id = ? AND session_id = ? AND timestamp >= ?
ORDER BY timestamp ASC
`

type GetEventsAfterTimestampParams struct {
	AppName   string
	UserID    string
	SessionID string
	Timestamp time.Time
}

func (q *Queries) GetEventsAfterTimestamp(ctx context.Context, arg GetEventsAfterTimestampParams) ([]SessionEvent, error) {
	rows, err := q.db.QueryContext(ctx, getEventsAfterTimestamp,
		arg.AppName,
		arg.UserID,
		arg.SessionID,
		arg.Timestamp,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionEvent
	for rows.Next() {
		var i SessionEvent
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.AppName,
			&i.UserID,
			&i.EventJson,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventsBySession = `-- name: GetEventsBySession :many
SELECT id, session_id, app_name, user_id, event_json, timestamp
FROM session_events
WHERE app_name = ? AND user_id = ? AND session_id = ?
ORDER BY timestamp ASC
`

type GetEventsBySessionParams struct {
	AppName   string
	UserID    string
	SessionID string
}

func (q *Queries) GetEventsBySession(ctx context.Context, arg GetEventsBySessionParams) ([]SessionEvent, error) {
	rows, err := q.db.QueryContext(ctx, getEventsBySession, arg.AppName, arg.UserID, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionEvent
	for rows.Next() {
		var i SessionEvent
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.AppName,
			&i.UserID,
			&i.EventJson,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentEventsBySession = `-- name: GetRecentEventsBySession :many
SELECT id, session_id, app_name, user_id, event_json, timestamp
FROM session_events
WHERE app_name = ? AND user_id = ? AND session_id = ?
ORDER BY timestamp DESC
LIMIT ?
`

type GetRecentEventsBySessionParams struct {
	AppName   string
	UserID    string
	SessionID string
	Limit     int64
}

func (q *Queries) GetRecentEventsBySession(ctx context.Context, arg GetRecentEventsBySessionParams) ([]SessionEvent, error) {
	rows, err := q.db.QueryContext(ctx, getRecentEventsBySession,
		arg.AppName,
		arg.UserID,
		arg.SessionID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionEvent
	for rows.Next() {
		var i SessionEvent
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.AppName,
			&i.UserID,
			&i.EventJson,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSession = `-- name: GetSession :one
SELECT session_id, app_name, user_id, state, created_at, updated_at
FROM sessions
WHERE app_name = ? AND user_id = ? AND session_id = ?
`

type GetSessionParams struct {
	AppName   string
	UserID    string
	SessionID string
}

func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, arg.AppName, arg.UserID, arg.SessionID)
	var i Session
	err := row.Scan(
		&i.SessionID,
		&i.AppName,
		&i.UserID,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserState = `-- name: GetUserState :one
SELECT state FROM user_states WHERE app_name = ? AND user_id = ?
`

type GetUserStateParams struct {
	AppName string
	UserID  string
}

func (q *Queries) GetUserState(ctx context.Context, arg GetUserStateParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserState, arg.AppName, arg.UserID)
	var state string
	err := row.Scan(&state)
	return state, err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO session_events (id, session_id, app_name, user_id, event_json, timestamp)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertEventParams struct {
	ID        string
	SessionID string
	AppName   string
	UserID    string
	EventJson string
	Timestamp time.Time
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.ExecContext(ctx, insertEvent,
		arg.ID,
		arg.SessionID,
		arg.AppName,
		arg.UserID,
		arg.EventJson,
		arg.Timestamp,
	)
	return err
}

const listSessionsByApp = `-- name: ListSessionsByApp :many
SELECT session_id, app_name, user_id, state, created_at, updated_at
FROM sessions
WHERE app_name = ?
ORDER BY updated_at DESC
`

func (q *Queries) ListSessionsByApp(ctx context.Context, appName string) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByApp, appName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.SessionID,
			&i.AppName,
			&i.UserID,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByUser = `-- name: ListSessionsByUser :many
SELECT session_id, app_name, user_id, state, created_at, updated_at
FROM sessions
WHERE app_name = ? AND user_id = ?
ORDER BY updated_at DESC
`

type ListSessionsByUserParams struct {
	AppName string
	UserID  string
}

func (q *Queries) ListSessionsByUser(ctx context.Context, arg ListSessionsByUserParams) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByUser, arg.AppName, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.SessionID,
			&i.AppName,
			&i.UserID,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionState = `-- name: UpdateSessionState :exec
UPDATE sessions
SET state = ?, updated_at = CURRENT_TIMESTAMP
WHERE app_name = ? AND user_id = ? AND session_id = ?
`

type UpdateSessionStateParams struct {
	State     string
	AppName   string
	UserID    string
	SessionID string
}

func (q *Queries) UpdateSessionState(ctx context.Context, arg UpdateSessionStateParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionState,
		arg.State,
		arg.AppName,
		arg.UserID,
		arg.SessionID,
	)
	return err
}

const upsertAppState = `-- name: UpsertAppState :exec
INSERT INTO app_states (app_name, state, updated_at)
VALUES (?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(app_name) DO UPDATE SET
    state      = excluded.state,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertAppStateParams struct {
	AppName string
	State   string
}

func (q *Queries) UpsertAppState(ctx context.Context, arg UpsertAppStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertAppState, arg.AppName, arg.State)
	return err
}

const upsertUserState = `-- name: UpsertUserState :exec
INSERT INTO user_states (app_name, user_id, state, updated_at)
VALUES (?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(app_name, user_id) DO UPDATE SET
    state      = excluded.state,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertUserStateParams struct {
	AppName string
	UserID  string
	State   string
}

func (q *Queries) UpsertUserState(ctx context.Context, arg UpsertUserStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserState, arg.AppName, arg.UserID, arg.State)
	return err
}
